/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export declare namespace BaseObject {
  export type SizeStruct = {
    x: BigNumberish;
    y: BigNumberish;
    z: BigNumberish;
  };

  export type SizeStructOutput = [number, number, number] & {
    x: number;
    y: number;
    z: number;
  };

  export type ObjectStruct = {
    tokenURI: string;
    size: BaseObject.SizeStruct;
    creator: string;
    maxClaimed: BigNumberish;
    price: BigNumberish;
    exp: BigNumberish;
    forSale: boolean;
  };

  export type ObjectStructOutput = [
    string,
    BaseObject.SizeStructOutput,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    tokenURI: string;
    size: BaseObject.SizeStructOutput;
    creator: string;
    maxClaimed: BigNumber;
    price: BigNumber;
    exp: BigNumber;
    forSale: boolean;
  };
}

export interface BaseObjectInterface extends utils.Interface {
  functions: {
    "allObjects(uint256)": FunctionFragment;
    "baseMetadataURI()": FunctionFragment;
    "changeTokenPrice(uint256,uint256)": FunctionFragment;
    "created(uint256)": FunctionFragment;
    "getBaseMetadataURI()": FunctionFragment;
    "getCreatorAddress(uint256)": FunctionFragment;
    "getExp(uint256)": FunctionFragment;
    "getMaxClaimed(uint256)": FunctionFragment;
    "getObjectInfo(uint256)": FunctionFragment;
    "getOpenForSale(uint256)": FunctionFragment;
    "getRoyalityFee()": FunctionFragment;
    "getSize(uint256)": FunctionFragment;
    "getTokenPrice(uint256)": FunctionFragment;
    "getTokenURI(uint256)": FunctionFragment;
    "getTreasuryAddress()": FunctionFragment;
    "name()": FunctionFragment;
    "ownerCheck(address)": FunctionFragment;
    "paymentBalanceOwner()": FunctionFragment;
    "removeOwner(address)": FunctionFragment;
    "royalityFee()": FunctionFragment;
    "royaltyInfo(uint256,uint256)": FunctionFragment;
    "secondaryRoyalty()": FunctionFragment;
    "setCreatorAddress(uint256,address)": FunctionFragment;
    "setExp(uint256,uint256)": FunctionFragment;
    "setMaxClaimed(uint256,uint256)": FunctionFragment;
    "setOpenForSale(uint256,bool)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "setRoyalityFee(uint256)": FunctionFragment;
    "setSecondaryRoyalityFee(uint256)": FunctionFragment;
    "setShopAddress(address)": FunctionFragment;
    "setSize(uint256,(uint8,uint8,uint8))": FunctionFragment;
    "setTokenURI(uint256,string)": FunctionFragment;
    "setTreasuryAddress(address)": FunctionFragment;
    "setbaseMetadataURI(string)": FunctionFragment;
    "shopAddress()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "symbol()": FunctionFragment;
    "treasuryAddress()": FunctionFragment;
    "withdrawOwnerBalance(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allObjects"
      | "baseMetadataURI"
      | "changeTokenPrice"
      | "created"
      | "getBaseMetadataURI"
      | "getCreatorAddress"
      | "getExp"
      | "getMaxClaimed"
      | "getObjectInfo"
      | "getOpenForSale"
      | "getRoyalityFee"
      | "getSize"
      | "getTokenPrice"
      | "getTokenURI"
      | "getTreasuryAddress"
      | "name"
      | "ownerCheck"
      | "paymentBalanceOwner"
      | "removeOwner"
      | "royalityFee"
      | "royaltyInfo"
      | "secondaryRoyalty"
      | "setCreatorAddress"
      | "setExp"
      | "setMaxClaimed"
      | "setOpenForSale"
      | "setOwner"
      | "setRoyalityFee"
      | "setSecondaryRoyalityFee"
      | "setShopAddress"
      | "setSize"
      | "setTokenURI"
      | "setTreasuryAddress"
      | "setbaseMetadataURI"
      | "shopAddress"
      | "supportsInterface"
      | "symbol"
      | "treasuryAddress"
      | "withdrawOwnerBalance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allObjects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "baseMetadataURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeTokenPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "created",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBaseMetadataURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getExp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxClaimed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getObjectInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpenForSale",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoyalityFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "ownerCheck", values: [string]): string;
  encodeFunctionData(
    functionFragment: "paymentBalanceOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "removeOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "royalityFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyInfo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "secondaryRoyalty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorAddress",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setExp",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxClaimed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOpenForSale",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setRoyalityFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSecondaryRoyalityFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setShopAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSize",
    values: [BigNumberish, BaseObject.SizeStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setbaseMetadataURI",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "shopAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawOwnerBalance",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "allObjects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "created", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBaseMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getExp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMaxClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getObjectInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOpenForSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoyalityFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerCheck", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentBalanceOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royalityFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "secondaryRoyalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setExp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOpenForSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRoyalityFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSecondaryRoyalityFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setShopAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setbaseMetadataURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shopAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawOwnerBalance",
    data: BytesLike
  ): Result;

  events: {
    "ChangeTokenPrice(uint256,uint256)": EventFragment;
    "OwnershipGranted(address,address)": EventFragment;
    "OwnershipRemoved(address,address)": EventFragment;
    "PaymentReceivedOwner(uint256)": EventFragment;
    "PaymentWithdrawnOwner(uint256)": EventFragment;
    "SetCreator(uint256,address)": EventFragment;
    "SetExp(uint256,uint256)": EventFragment;
    "SetMaxClaimed(uint256,uint256)": EventFragment;
    "SetOpenForSale(uint256,bool)": EventFragment;
    "SetRoyalityFee(uint256)": EventFragment;
    "SetSecondaryRoyalityFee(uint256)": EventFragment;
    "SetShopAddress(address)": EventFragment;
    "SetSize(uint256,uint8,uint8,uint8)": EventFragment;
    "SetTokenURI(uint256,string)": EventFragment;
    "SetTreasuryAddress(address)": EventFragment;
    "SetbaseMetadataURI(string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChangeTokenPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaymentReceivedOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaymentWithdrawnOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetCreator"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetExp"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMaxClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetOpenForSale"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetRoyalityFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetSecondaryRoyalityFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetShopAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetSize"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetTokenURI"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetTreasuryAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetbaseMetadataURI"): EventFragment;
}

export interface ChangeTokenPriceEventObject {
  tokenId: BigNumber;
  newPrice: BigNumber;
}
export type ChangeTokenPriceEvent = TypedEvent<
  [BigNumber, BigNumber],
  ChangeTokenPriceEventObject
>;

export type ChangeTokenPriceEventFilter =
  TypedEventFilter<ChangeTokenPriceEvent>;

export interface OwnershipGrantedEventObject {
  operator: string;
  target: string;
}
export type OwnershipGrantedEvent = TypedEvent<
  [string, string],
  OwnershipGrantedEventObject
>;

export type OwnershipGrantedEventFilter =
  TypedEventFilter<OwnershipGrantedEvent>;

export interface OwnershipRemovedEventObject {
  operator: string;
  target: string;
}
export type OwnershipRemovedEvent = TypedEvent<
  [string, string],
  OwnershipRemovedEventObject
>;

export type OwnershipRemovedEventFilter =
  TypedEventFilter<OwnershipRemovedEvent>;

export interface PaymentReceivedOwnerEventObject {
  amount: BigNumber;
}
export type PaymentReceivedOwnerEvent = TypedEvent<
  [BigNumber],
  PaymentReceivedOwnerEventObject
>;

export type PaymentReceivedOwnerEventFilter =
  TypedEventFilter<PaymentReceivedOwnerEvent>;

export interface PaymentWithdrawnOwnerEventObject {
  amount: BigNumber;
}
export type PaymentWithdrawnOwnerEvent = TypedEvent<
  [BigNumber],
  PaymentWithdrawnOwnerEventObject
>;

export type PaymentWithdrawnOwnerEventFilter =
  TypedEventFilter<PaymentWithdrawnOwnerEvent>;

export interface SetCreatorEventObject {
  tokenId: BigNumber;
  creator: string;
}
export type SetCreatorEvent = TypedEvent<
  [BigNumber, string],
  SetCreatorEventObject
>;

export type SetCreatorEventFilter = TypedEventFilter<SetCreatorEvent>;

export interface SetExpEventObject {
  tokenId: BigNumber;
  exp: BigNumber;
}
export type SetExpEvent = TypedEvent<[BigNumber, BigNumber], SetExpEventObject>;

export type SetExpEventFilter = TypedEventFilter<SetExpEvent>;

export interface SetMaxClaimedEventObject {
  tokenId: BigNumber;
  newMaxClaimed: BigNumber;
}
export type SetMaxClaimedEvent = TypedEvent<
  [BigNumber, BigNumber],
  SetMaxClaimedEventObject
>;

export type SetMaxClaimedEventFilter = TypedEventFilter<SetMaxClaimedEvent>;

export interface SetOpenForSaleEventObject {
  tokenId: BigNumber;
  check: boolean;
}
export type SetOpenForSaleEvent = TypedEvent<
  [BigNumber, boolean],
  SetOpenForSaleEventObject
>;

export type SetOpenForSaleEventFilter = TypedEventFilter<SetOpenForSaleEvent>;

export interface SetRoyalityFeeEventObject {
  royalityFee: BigNumber;
}
export type SetRoyalityFeeEvent = TypedEvent<
  [BigNumber],
  SetRoyalityFeeEventObject
>;

export type SetRoyalityFeeEventFilter = TypedEventFilter<SetRoyalityFeeEvent>;

export interface SetSecondaryRoyalityFeeEventObject {
  secondaryRoyalty: BigNumber;
}
export type SetSecondaryRoyalityFeeEvent = TypedEvent<
  [BigNumber],
  SetSecondaryRoyalityFeeEventObject
>;

export type SetSecondaryRoyalityFeeEventFilter =
  TypedEventFilter<SetSecondaryRoyalityFeeEvent>;

export interface SetShopAddressEventObject {
  shopAddress: string;
}
export type SetShopAddressEvent = TypedEvent<
  [string],
  SetShopAddressEventObject
>;

export type SetShopAddressEventFilter = TypedEventFilter<SetShopAddressEvent>;

export interface SetSizeEventObject {
  tokenId: BigNumber;
  x: number;
  y: number;
  z: number;
}
export type SetSizeEvent = TypedEvent<
  [BigNumber, number, number, number],
  SetSizeEventObject
>;

export type SetSizeEventFilter = TypedEventFilter<SetSizeEvent>;

export interface SetTokenURIEventObject {
  tokenId: BigNumber;
  uri: string;
}
export type SetTokenURIEvent = TypedEvent<
  [BigNumber, string],
  SetTokenURIEventObject
>;

export type SetTokenURIEventFilter = TypedEventFilter<SetTokenURIEvent>;

export interface SetTreasuryAddressEventObject {
  treasuryAddress: string;
}
export type SetTreasuryAddressEvent = TypedEvent<
  [string],
  SetTreasuryAddressEventObject
>;

export type SetTreasuryAddressEventFilter =
  TypedEventFilter<SetTreasuryAddressEvent>;

export interface SetbaseMetadataURIEventObject {
  baseuri: string;
}
export type SetbaseMetadataURIEvent = TypedEvent<
  [string],
  SetbaseMetadataURIEventObject
>;

export type SetbaseMetadataURIEventFilter =
  TypedEventFilter<SetbaseMetadataURIEvent>;

export interface BaseObject extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BaseObjectInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allObjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BaseObject.SizeStructOutput,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        tokenURI: string;
        size: BaseObject.SizeStructOutput;
        creator: string;
        maxClaimed: BigNumber;
        price: BigNumber;
        exp: BigNumber;
        forSale: boolean;
      }
    >;

    baseMetadataURI(overrides?: CallOverrides): Promise<[string]>;

    changeTokenPrice(
      tokenId: BigNumberish,
      newPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    created(arg0: BigNumberish, overrides?: CallOverrides): Promise<[boolean]>;

    getBaseMetadataURI(overrides?: CallOverrides): Promise<[string]>;

    getCreatorAddress(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getExp(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getMaxClaimed(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getObjectInfo(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BaseObject.ObjectStructOutput]>;

    getOpenForSale(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getRoyalityFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSize(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BaseObject.SizeStructOutput]>;

    getTokenPrice(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTreasuryAddress(overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    ownerCheck(
      targetAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    paymentBalanceOwner(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeOwner(
      oldOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    royalityFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    royaltyInfo(
      arg0: BigNumberish,
      salePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { receiver: string; royaltyAmount: BigNumber }
    >;

    secondaryRoyalty(overrides?: CallOverrides): Promise<[BigNumber]>;

    setCreatorAddress(
      tokenId: BigNumberish,
      creator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setExp(
      tokenId: BigNumberish,
      exp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMaxClaimed(
      tokenId: BigNumberish,
      newMaxClaimed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOpenForSale(
      tokenId: BigNumberish,
      check: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRoyalityFee(
      newRoyalityFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSecondaryRoyalityFee(
      newSecondaryRoyalty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setShopAddress(
      _shopAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSize(
      tokenId: BigNumberish,
      size: BaseObject.SizeStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenURI(
      tokenId: BigNumberish,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTreasuryAddress(
      newTreasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setbaseMetadataURI(
      newBaseMetadataURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    shopAddress(overrides?: CallOverrides): Promise<[string]>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    treasuryAddress(overrides?: CallOverrides): Promise<[string]>;

    withdrawOwnerBalance(
      withdrawTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  allObjects(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      BaseObject.SizeStructOutput,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean
    ] & {
      tokenURI: string;
      size: BaseObject.SizeStructOutput;
      creator: string;
      maxClaimed: BigNumber;
      price: BigNumber;
      exp: BigNumber;
      forSale: boolean;
    }
  >;

  baseMetadataURI(overrides?: CallOverrides): Promise<string>;

  changeTokenPrice(
    tokenId: BigNumberish,
    newPrice: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  created(arg0: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  getBaseMetadataURI(overrides?: CallOverrides): Promise<string>;

  getCreatorAddress(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getExp(tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  getMaxClaimed(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getObjectInfo(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BaseObject.ObjectStructOutput>;

  getOpenForSale(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getRoyalityFee(overrides?: CallOverrides): Promise<BigNumber>;

  getSize(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BaseObject.SizeStructOutput>;

  getTokenPrice(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTokenURI(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getTreasuryAddress(overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  ownerCheck(
    targetAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  paymentBalanceOwner(overrides?: CallOverrides): Promise<BigNumber>;

  removeOwner(
    oldOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  royalityFee(overrides?: CallOverrides): Promise<BigNumber>;

  royaltyInfo(
    arg0: BigNumberish,
    salePrice: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber] & { receiver: string; royaltyAmount: BigNumber }
  >;

  secondaryRoyalty(overrides?: CallOverrides): Promise<BigNumber>;

  setCreatorAddress(
    tokenId: BigNumberish,
    creator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setExp(
    tokenId: BigNumberish,
    exp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMaxClaimed(
    tokenId: BigNumberish,
    newMaxClaimed: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOpenForSale(
    tokenId: BigNumberish,
    check: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setOwner(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRoyalityFee(
    newRoyalityFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSecondaryRoyalityFee(
    newSecondaryRoyalty: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setShopAddress(
    _shopAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSize(
    tokenId: BigNumberish,
    size: BaseObject.SizeStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenURI(
    tokenId: BigNumberish,
    uri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTreasuryAddress(
    newTreasuryAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setbaseMetadataURI(
    newBaseMetadataURI: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  shopAddress(overrides?: CallOverrides): Promise<string>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  symbol(overrides?: CallOverrides): Promise<string>;

  treasuryAddress(overrides?: CallOverrides): Promise<string>;

  withdrawOwnerBalance(
    withdrawTo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allObjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        BaseObject.SizeStructOutput,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean
      ] & {
        tokenURI: string;
        size: BaseObject.SizeStructOutput;
        creator: string;
        maxClaimed: BigNumber;
        price: BigNumber;
        exp: BigNumber;
        forSale: boolean;
      }
    >;

    baseMetadataURI(overrides?: CallOverrides): Promise<string>;

    changeTokenPrice(
      tokenId: BigNumberish,
      newPrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    created(arg0: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    getBaseMetadataURI(overrides?: CallOverrides): Promise<string>;

    getCreatorAddress(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getExp(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMaxClaimed(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getObjectInfo(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BaseObject.ObjectStructOutput>;

    getOpenForSale(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getRoyalityFee(overrides?: CallOverrides): Promise<BigNumber>;

    getSize(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BaseObject.SizeStructOutput>;

    getTokenPrice(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getTreasuryAddress(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    ownerCheck(
      targetAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    paymentBalanceOwner(overrides?: CallOverrides): Promise<BigNumber>;

    removeOwner(oldOwner: string, overrides?: CallOverrides): Promise<void>;

    royalityFee(overrides?: CallOverrides): Promise<BigNumber>;

    royaltyInfo(
      arg0: BigNumberish,
      salePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { receiver: string; royaltyAmount: BigNumber }
    >;

    secondaryRoyalty(overrides?: CallOverrides): Promise<BigNumber>;

    setCreatorAddress(
      tokenId: BigNumberish,
      creator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setExp(
      tokenId: BigNumberish,
      exp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxClaimed(
      tokenId: BigNumberish,
      newMaxClaimed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setOpenForSale(
      tokenId: BigNumberish,
      check: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setOwner(newOwner: string, overrides?: CallOverrides): Promise<void>;

    setRoyalityFee(
      newRoyalityFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSecondaryRoyalityFee(
      newSecondaryRoyalty: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setShopAddress(
      _shopAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSize(
      tokenId: BigNumberish,
      size: BaseObject.SizeStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenURI(
      tokenId: BigNumberish,
      uri: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTreasuryAddress(
      newTreasuryAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setbaseMetadataURI(
      newBaseMetadataURI: string,
      overrides?: CallOverrides
    ): Promise<void>;

    shopAddress(overrides?: CallOverrides): Promise<string>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    treasuryAddress(overrides?: CallOverrides): Promise<string>;

    withdrawOwnerBalance(
      withdrawTo: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ChangeTokenPrice(uint256,uint256)"(
      tokenId?: null,
      newPrice?: null
    ): ChangeTokenPriceEventFilter;
    ChangeTokenPrice(
      tokenId?: null,
      newPrice?: null
    ): ChangeTokenPriceEventFilter;

    "OwnershipGranted(address,address)"(
      operator?: string | null,
      target?: string | null
    ): OwnershipGrantedEventFilter;
    OwnershipGranted(
      operator?: string | null,
      target?: string | null
    ): OwnershipGrantedEventFilter;

    "OwnershipRemoved(address,address)"(
      operator?: string | null,
      target?: string | null
    ): OwnershipRemovedEventFilter;
    OwnershipRemoved(
      operator?: string | null,
      target?: string | null
    ): OwnershipRemovedEventFilter;

    "PaymentReceivedOwner(uint256)"(
      amount?: null
    ): PaymentReceivedOwnerEventFilter;
    PaymentReceivedOwner(amount?: null): PaymentReceivedOwnerEventFilter;

    "PaymentWithdrawnOwner(uint256)"(
      amount?: null
    ): PaymentWithdrawnOwnerEventFilter;
    PaymentWithdrawnOwner(amount?: null): PaymentWithdrawnOwnerEventFilter;

    "SetCreator(uint256,address)"(
      tokenId?: null,
      creator?: null
    ): SetCreatorEventFilter;
    SetCreator(tokenId?: null, creator?: null): SetCreatorEventFilter;

    "SetExp(uint256,uint256)"(tokenId?: null, exp?: null): SetExpEventFilter;
    SetExp(tokenId?: null, exp?: null): SetExpEventFilter;

    "SetMaxClaimed(uint256,uint256)"(
      tokenId?: null,
      newMaxClaimed?: null
    ): SetMaxClaimedEventFilter;
    SetMaxClaimed(
      tokenId?: null,
      newMaxClaimed?: null
    ): SetMaxClaimedEventFilter;

    "SetOpenForSale(uint256,bool)"(
      tokenId?: null,
      check?: null
    ): SetOpenForSaleEventFilter;
    SetOpenForSale(tokenId?: null, check?: null): SetOpenForSaleEventFilter;

    "SetRoyalityFee(uint256)"(royalityFee?: null): SetRoyalityFeeEventFilter;
    SetRoyalityFee(royalityFee?: null): SetRoyalityFeeEventFilter;

    "SetSecondaryRoyalityFee(uint256)"(
      secondaryRoyalty?: null
    ): SetSecondaryRoyalityFeeEventFilter;
    SetSecondaryRoyalityFee(
      secondaryRoyalty?: null
    ): SetSecondaryRoyalityFeeEventFilter;

    "SetShopAddress(address)"(shopAddress?: null): SetShopAddressEventFilter;
    SetShopAddress(shopAddress?: null): SetShopAddressEventFilter;

    "SetSize(uint256,uint8,uint8,uint8)"(
      tokenId?: null,
      x?: null,
      y?: null,
      z?: null
    ): SetSizeEventFilter;
    SetSize(tokenId?: null, x?: null, y?: null, z?: null): SetSizeEventFilter;

    "SetTokenURI(uint256,string)"(
      tokenId?: null,
      uri?: null
    ): SetTokenURIEventFilter;
    SetTokenURI(tokenId?: null, uri?: null): SetTokenURIEventFilter;

    "SetTreasuryAddress(address)"(
      treasuryAddress?: null
    ): SetTreasuryAddressEventFilter;
    SetTreasuryAddress(treasuryAddress?: null): SetTreasuryAddressEventFilter;

    "SetbaseMetadataURI(string)"(baseuri?: null): SetbaseMetadataURIEventFilter;
    SetbaseMetadataURI(baseuri?: null): SetbaseMetadataURIEventFilter;
  };

  estimateGas: {
    allObjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baseMetadataURI(overrides?: CallOverrides): Promise<BigNumber>;

    changeTokenPrice(
      tokenId: BigNumberish,
      newPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    created(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    getBaseMetadataURI(overrides?: CallOverrides): Promise<BigNumber>;

    getCreatorAddress(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getExp(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMaxClaimed(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getObjectInfo(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOpenForSale(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoyalityFee(overrides?: CallOverrides): Promise<BigNumber>;

    getSize(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenPrice(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTreasuryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    ownerCheck(
      targetAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    paymentBalanceOwner(overrides?: CallOverrides): Promise<BigNumber>;

    removeOwner(
      oldOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    royalityFee(overrides?: CallOverrides): Promise<BigNumber>;

    royaltyInfo(
      arg0: BigNumberish,
      salePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    secondaryRoyalty(overrides?: CallOverrides): Promise<BigNumber>;

    setCreatorAddress(
      tokenId: BigNumberish,
      creator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setExp(
      tokenId: BigNumberish,
      exp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMaxClaimed(
      tokenId: BigNumberish,
      newMaxClaimed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOpenForSale(
      tokenId: BigNumberish,
      check: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRoyalityFee(
      newRoyalityFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSecondaryRoyalityFee(
      newSecondaryRoyalty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setShopAddress(
      _shopAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSize(
      tokenId: BigNumberish,
      size: BaseObject.SizeStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenURI(
      tokenId: BigNumberish,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTreasuryAddress(
      newTreasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setbaseMetadataURI(
      newBaseMetadataURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    shopAddress(overrides?: CallOverrides): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    treasuryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawOwnerBalance(
      withdrawTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allObjects(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    baseMetadataURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeTokenPrice(
      tokenId: BigNumberish,
      newPrice: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    created(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBaseMetadataURI(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCreatorAddress(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getExp(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMaxClaimed(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getObjectInfo(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOpenForSale(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoyalityFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSize(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenPrice(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTreasuryAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerCheck(
      targetAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    paymentBalanceOwner(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeOwner(
      oldOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    royalityFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    royaltyInfo(
      arg0: BigNumberish,
      salePrice: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    secondaryRoyalty(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setCreatorAddress(
      tokenId: BigNumberish,
      creator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setExp(
      tokenId: BigNumberish,
      exp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMaxClaimed(
      tokenId: BigNumberish,
      newMaxClaimed: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOpenForSale(
      tokenId: BigNumberish,
      check: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setOwner(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRoyalityFee(
      newRoyalityFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSecondaryRoyalityFee(
      newSecondaryRoyalty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setShopAddress(
      _shopAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSize(
      tokenId: BigNumberish,
      size: BaseObject.SizeStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenURI(
      tokenId: BigNumberish,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTreasuryAddress(
      newTreasuryAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setbaseMetadataURI(
      newBaseMetadataURI: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    shopAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    treasuryAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawOwnerBalance(
      withdrawTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
