/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BasePlate__factory } from "./BasePlate__factory";
export { FreeObject__factory } from "./FreeObject__factory";
export { PremiumObject__factory } from "./PremiumObject__factory";
export { QuestObject__factory } from "./QuestObject__factory";
export { WallPaper__factory } from "./WallPaper__factory";
