/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BasePlate } from "./BasePlate";
export type { FreeObject } from "./FreeObject";
export type { PremiumObject } from "./PremiumObject";
export type { QuestObject } from "./QuestObject";
export type { WallPaper } from "./WallPaper";
